{
 "title": "RoadRunner HTTP dashboard",
 "description": "RoadRunner HTTP dashboard (http plugin with `http_metrics` middleware).",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RR uptime 3",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rr_http_uptime_seconds{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "RR in-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "HTTP Workers state",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rr_http_total_workers{namespace=~\"$namespace\",pod=~\"$pod\"}) by (le)",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(rr_http_workers_ready{namespace=~\"$namespace\",pod=~\"$pod\"}) by (le)",
     "legendFormat": "READY"
    },
    {
     "expr": "sum(rr_http_workers_working{namespace=~\"$namespace\",pod=~\"$pod\"}) by (le)",
     "legendFormat": "WORKING"
    },
    {
     "expr": "sum(rr_http_workers_invalid{namespace=~\"$namespace\",pod=~\"$pod\"}) by (le)",
     "legendFormat": "INVALID"
    }
   ]
  },
  {
   "title": "Workers total memory [HTTP]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_http_workers_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\"} /1024000)",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory by worker [HTTP]",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rr_http_worker_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "PID: {{pid}}"
    }
   ]
  },
  {
   "title": "HTTP latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rr_http_request_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP requests queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rr_http_requests_queue{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "RPM [HTTP]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(rr_http_request_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  }
 ]
}